# Generated by Django 5.1.3 on 2024-11-30 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_messages_messages_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
